apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: main-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend
spec:
  hosts:
  - '*'
  gateways:
  - main-gateway
  http:
  - match:
    - uri:
        exact: /
    - uri:
        exact: /index
    route:
    - destination:
        host: frontend-svc
        port:
          number: 5000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: count
spec:
  hosts:
  - count-svc
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: count-svc
        subset: v1
        port:
          number: 5001
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fix-messages
spec:
  hosts:
  - fix-messages-svc
  http:
  - route:
    - destination:
        host: fix-messages-svc
        subset: v2
      weight: 20
    - destination:
        host: fix-messages-svc
        subset: v1
      weight: 80
        