apiVersion: apps/v1
kind: Deployment
metadata:
  name: messages-deploymentv1
  labels:
    app: messages
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messages
      version: v1
  template:
    metadata:
      labels:
        app: messages
        version: v1
    spec:
      serviceAccountName: messages-acc
      containers:
      - name: messages
        image: koraven/messages:2
        imagePullPolicy: Always
        env:
          - name: DB_HOSTNAME
            value: postgres-postgresql
        ports:
        - containerPort: 5003

---
apiVersion: v1
kind: Service
metadata:
  name: messages-svc
  labels:
    app: messages
    service: messages-svc
spec:
  selector:
    app: messages
  ports:
  - port: 5003
    name: http
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: messages-acc
  labels:
    account: messages