apiVersion: v1
kind: Service
metadata:
  name: count-svc
  labels:
    app: count
    service: count-svc
spec:
  selector:
    app: count
  ports:
  - port: 5000
    name: http
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: count-acc
  labels:
    account: count